# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

windowrule = match:workspace w[t1], border_size 0
windowrule = match:fullscreen true, border_size 0
